# install and load the stringr and dplyr packages if they're not already installed
#install.packages(c("stringr", "dplyr"))
library(stringr)
library(dplyr)
library(readr)
library(quanteda)
library(quanteda.textplots)
library(quanteda.textstats)
library(tidytext)
library(dplyr)
library(ggplot2)
library(broom)
library(ggwordcloud)
library(igraph)
library(quanteda)
library(quanteda.textstats)
library(quanteda.textplots)
library(stringr)

RecipeNLG_dataset <- read_csv("data-raw/Recipe_new.csv")
hunder_rows <- head(RecipeNLG_dataset, 1000)

ingredient_sep <- unlist(str_extract_all(hunder_rows$NER,  "\"([^\"]*)\""))
ingredient_sep <- gsub("\"", "", ingredient_sep)
